### ISSUE TITLE
Use '.svelte' for components in documentation rather than '.html'

### ISSUE THREAD

**Issue by mikemaccana** [sveltejs/v2.svelte.dev#332]
(Moved from https://github.com/sveltejs/svelte/issues/1602)

Reading the docs, https://svelte.technology/guide#understanding-svelte-components, `.html` is used as a file extension for svelte components.

Since everything is inside a tag, yes, the files are (template syntax aside) HTML. However

 - Most web developers would not consider JS and CSS 'HTML', even wrapped in tags
 - `.html` does not illustrate well that Svelte components include JS and CSS
 - `.html` is typically used for HTML, not HTML with Svelte's template language

Much like vue uses `.vue` for Vue components, it may be clearer for users for Svelte to use `.svelte`

**Comment by Rich-Harris** [comment]
This is perhaps best answered with a screenshot:

<img width="699" alt="screen shot 2018-07-19 at 3 53 52 pm" src="https://user-images.githubusercontent.com/1162160/42966678-f9544d4c-8b6b-11e8-8030-77c4623f81d0.png">

**Comment by mikemaccana** [comment]
Yeah, you'll get limited syntax highlighting with a html extension, but
users will/should install a Svelte specific syntax highlighter anyway (and
a modern editor will even suggest one for a new file extension - which they
won't for html).

**Comment by Rich-Harris** [comment]
I don't like the trend towards requiring that people change their development practices to accommodate a framework — an extension is a commitment that people aren't necessarily ready to make. It's presumptuous, as is expecting people to use an editor that has a suitable extension (so far the only extension I'm aware of is the VSCode one, which I disabled for the screenshot above). An extension is also another moving part that needs to be maintained.

Afraid I can't agree with bullet points 1 and 2, which are essentially the same thing. I can't imagine a web app developer not being well aware that an HTML file can contain `<style>` and `<script>`! As for point 3, that's true (though the hope is that other frameworks besides Svelte adopt [HTMLx](https://github.com/rich-harris/htmlx) — watch this space), but it's no weirder than people writing JSX in .js files, which is extremely common.

**Comment by paulocoghi** [comment]
> It's not that they're not aware HTML /can't/ include these things, it's just that they're used to seeing these things in head or before end of body, not inline as part of a component. When I think of an '.html' file, I literally think of HTML. I'm sure I'm not the only one.

I am using Ractive since 2015 (which is kind of the "predecessor" of Svelte). Since that time it has implemented the same concept of HTML components that can contain `<style>` and `<script>` tags, and it is awesome.

I do not remember where Rich Harris wrote about it for the first time, but this concept is really nice (IMHO) and has been very well accepted in all these years on both Ractive and Svelte community.

**Comment by mikemaccana** [comment]
@paulocoghi Yep, also a ractive user - though started earlier so tend to use ES6 template strings to hold the mustache - and I like the one-component-per-file concept too. I just don't think .HTML is the right extension for the reasons already mentioned above.

**Comment by Rich-Harris** [comment]
Yeah, Mike is an old-school Ractivist and a great friend to the project. He was the one who prodded me to claim the RactiveJS Twitter account, 5 years ago this month! 😱 

> What commitment is required?

Firstly the commitment to use VSCode, at least until there are plugins for other editors. If you're already in that boat, then it's fairly simple to install the extension, but you have to think about it in terms of conversion rates.

Imagine I'm interested in getting a certificate with CertSimple. I go to https://certsimple.com and there's a really nice onboarding flow — you can fill out a few details right there on the homepage and you're on to the next step. Maybe it would be valuable to you to collect email addresses as part of that initial flow, so that you can contact people who drop out at later stages. Seems relatively painless. But maybe that would introduce enough friction that fewer people would click the 'get your certificate now' button, and your overall conversion rate would drop. 

I think about this the same way. I'm curious about this new framework I'm hearing about, and I decide to try it out. I have to wrap my head around using a compiler instead of importing a library — weird, but ok, I get it, that's the whole point. But what's this: now it's asking me to use a particular editor, and to install an extension?

1. Ok... I guess I'm interested enough that I'll jump through these hoops. After all, I'm already using VSCode, and it's easy to remove a plugin later, and it's probably trustworthy.
2. Hmm. This is starting to feel a bit... intrusive. I wonder what other hoops I'm going to have to jump through? Maybe I'll come back to it in a few months if people are still talking about it, I just wanted to quickly hack on something and try it out.

Which percentage of users is 1 and which is 2? If the answer isn't 100% vs 0% — which it certainly isn't — then the benefit from forcing that behaviour on users has to outweigh the costs of losing x% of them. It's almost impossible to quantify but I don't think 50% is unrealistic. In other words, the gains would have to be *huge*. And they're just not!

**Comment by scorsi** [comment]
Hello,

I'm coming from the React and VueJS community. I dive into Svelte after Inferno while I was looking for something faster/lighter (Inferno seems faster btw). And I am here.

Anyway, having its own extension allow to avoid the file to be interpreted as is by the HTML plugin. Furthermore, we could easily use .svelte and .html extensions by the svelte compiler (as today) and mixes them together. So if a plugin see the day, no problem, right ?
I'll try to build a Atom plugin for a svelte extension (see you in a year lol).

I will just give my point of view about the two options. 

## _HTML_ extension:
### GOOD:
 - No plugin for our editor, we can more **easily dive in/use Svelte**.
 - No plugin means **no maintenance**.
 - **Syntax highlighting sufficient** for standard uses (as long as we don't use preprocessors).
### BAD:
 - **Svelte attributes not understood** (as `on:click`, `bind:value`...) by majority of editor. WebStorm give a warning because XML namespace "on" and "bind" aren't included.
 - **No syntax highlighting and autocompletion for some case**: JS in HTML (outside the script part) and variable interpolation `{myVar}`.
 - **Poor (or non-existent) syntaxe highlighting when using preprocessors**. It's impossible to get syntax highlighting for Pug directly into our component, we have to use `<template src=...></template>` and put our Pug code into a separated file. It's the same case for Haml, CoffeeScript, TypeScript, Stylus, Sass, etc (just to quote some)...

## _SVELTE_ extension:
Obviously, the majority of bad point for HTML are good for Svelte extension and vice versa.
### GOOD:
 - **Perfect autocompletion and syntax highlighting** even with preprocessors (like for VueJS).
 - Seems more "professional": **indexed and understood** by GitHub (as for Vue).
### BAD:
 - Have **to be installed by the user and in some case change its editor**.
 - Maintenance for each plugins: WebStorm/Atom/VSCode for the best known. **Very time-consuming**.

**Comment by jfbrennan** [comment]
Would be great to see IDE plugins for Svelte, but I think the point is the work/mental load required to get all that set up should be an _opt-in_ experience for developers who come to Svelte. By default they should be able to throw Svelte into whatever build process they have (already a big ask when you compare to Vue or Riot), create a `my-component.html` file, and start coding without any hassle.

**Comment by Conduitry** [comment]
.svelte has been embraced in v3. We're not going to make changes like this in v2 at this point.

**Comment by mikemaccana** [comment]
Woo 😀

**Comment by StreetStrider** [comment]
`Component.svelte.html`. :thinking:
